# Generated by Django 4.2.10 on 2026-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_bonustransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
