# Generated by Django 4.2.10 on 2026-05-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_usermeasurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Причина отмены/возврата и т.д."
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bonus_level_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_spent_cached",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                    ("refunded", "Возврат"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bonus_level",
            field=models.CharField(
                choices=[
                    ("bronze", "Бронзовый"),
                    ("silver", "Серебряный"),
                    ("gold", "Золотой"),
                ],
                default="bronze",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Положительная — начисление, отрицательная — списание"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Начисление"),
                            ("spend", "Списание"),
                            ("cashback", "Кэшбэк"),
                            ("refund", "Возврат"),
                            ("adjust", "Корректировка"),
                            ("expire", "Списание по сроку"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        blank=True, help_text="Баланс после операции", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_transactions",
                        to="store.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
