# Generated by Django 4.2.10 on 2026-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_bonus_transaction_and_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("card", "Карта онлайн"), ("receiving", "При получении")],
                default="card",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(blank=True, default="courier", max_length=50),
        ),
    ]
