@startuml

start

:Просмотр каталога;

:Выбор товара;

if (Добавить в корзину?) then (Да)
  :Добавление в корзину;
else (Нет)
  stop
endif

:Оформление заказа;

if (Данные корректны?) then (Да)
  :Создание заказа;
  :Списание товара;
  :Подтверждение;
else (Нет)
  :Ошибка ввода;
endif

stop

@enduml